<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>MerlAIn.Api</RootNamespace>
    <UserSecretsId>merlain-api</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../libs/dotnet/MerlAIn.Shared/MerlAIn.Shared.csproj" />
  </ItemGroup>

</Project>
